.PHONY: clean All

All:
	@echo "----------Building project:[ Math - Debug ]----------"
	@cd "Math" && "$(MAKE)" -f  "Math.mk"
clean:
	@echo "----------Cleaning project:[ Math - Debug ]----------"
	@cd "Math" && "$(MAKE)" -f  "Math.mk" clean
